FBREF_HOMEPAGE_URL = "https://fbref.com/"
PREM_URL = "https://fbref.com/en/comps/9/Premier-League-Stats"
FBREF_MATCHES_URL_PATH = "en/matches/"
LEAGUE_TEAM_TABLE_ID = "results2022-202391_overall"
PREM_LEAGUE_SCORES_URL = "https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures"